language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t bigkevx2/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bigkevx2/docker-react npm run test
